import Foundation
import UIKit

class RecipeService: ObservableObject {
    @Published private(set) var recipes: [Recipe] = [
        Recipe(name: "Scrambled Eggs & Spinach",
               ingredients: ["2 eggs","1 cup spinach","1 tsp olive oil"],
               instructions: "Sauté spinach in oil; add beaten eggs; scramble until cooked.",
               calories: 200, protein: 16, carbs: 2, fat: 14),
        Recipe(name: "Greek Yogurt Parfait",
               ingredients: ["1 cup Greek yogurt","½ cup mixed berries","2 tbsp granola"],
               instructions: "Layer yogurt, berries, granola in a glass.",
               calories: 300, protein: 20, carbs: 30, fat: 8),
        Recipe(name: "Oatmeal with Banana & Nuts",
               ingredients: ["½ cup oats","1 banana","1 tbsp almonds"],
               instructions: "Cook oats; top with sliced banana and chopped almonds.",
               calories: 350, protein: 10, carbs: 60, fat: 10),
        Recipe(name: "Avocado Toast",
               ingredients: ["1 slice whole-grain bread","½ avocado","Sprinkle chili flakes"],
               instructions: "Toast bread; mash avocado; spread on toast; top with flakes.",
               calories: 250, protein: 6, carbs: 30, fat: 12),
        Recipe(name: "Protein Smoothie",
               ingredients: ["1 scoop whey protein","1 banana","1 cup almond milk"],
               instructions: "Blend everything until smooth.",
               calories: 260, protein: 25, carbs: 30, fat: 5),
        Recipe(name: "Chicken & Veggie Stir-Fry",
               ingredients: ["150g chicken breast","1 cup mixed veggies","2 tbsp soy sauce"],
               instructions: "Stir-fry chicken, add veggies and soy sauce, cook until done.",
               calories: 400, protein: 35, carbs: 12, fat: 18),
        Recipe(name: "Tuna Salad Wrap",
               ingredients: ["1 tortilla","100g tuna","Lettuce","Tomato"],
               instructions: "Mix tuna with a little mayo; fill tortilla with tuna and veggies; roll.",
               calories: 320, protein: 28, carbs: 30, fat: 8),
        Recipe(name: "Quinoa & Black Bean Bowl",
               ingredients: ["½ cup quinoa","½ cup black beans","Avocado","Salsa"],
               instructions: "Cook quinoa; mix with beans; top with diced avocado and salsa.",
               calories: 450, protein: 15, carbs: 60, fat: 15),
        Recipe(name: "Turkey Chili",
               ingredients: ["200g ground turkey","Beans","Tomato sauce","Spices"],
               instructions: "Brown turkey; add beans, sauce, spices; simmer 20 minutes.",
               calories: 380, protein: 32, carbs: 25, fat: 14),
        Recipe(name: "Baked Salmon & Asparagus",
               ingredients: ["150g salmon","1 cup asparagus","1 tsp olive oil"],
               instructions: "Bake salmon + asparagus at 180°C for 15-20 minutes.",
               calories: 420, protein: 35, carbs: 5, fat: 25),
        Recipe(name: "Beef & Broccoli",
               ingredients: ["150g beef strips","1 cup broccoli","2 tbsp oyster sauce"],
               instructions: "Stir-fry beef, add broccoli and sauce, cook until tender.",
               calories: 400, protein: 30, carbs: 10, fat: 22),
        Recipe(name: "Sweet Potato & Black Bean Tacos",
               ingredients: ["2 corn tortillas","½ cup sweet potato","½ cup black beans","Avocado"],
               instructions: "Roast sweet potato; fill tortillas with potato, beans, avocado.",
               calories: 360, protein: 12, carbs: 50, fat: 14),
        Recipe(name: "Fruit & Nut Trail Mix",
               ingredients: ["¼ cup almonds","¼ cup walnuts","¼ cup raisins","¼ cup dried cranberries"],
               instructions: "Combine everything in a bag.",
               calories: 300, protein: 7, carbs: 30, fat: 18),
        Recipe(name: "Egg & Veggie Muffins",
               ingredients: ["4 eggs","½ cup chopped veggies","Salt & pepper"],
               instructions: "Whisk eggs + veggies, divide into muffin tin, bake at 180°C 20 min.",
               calories: 180, protein: 12, carbs: 4, fat: 14),
        Recipe(name: "Cottage Cheese & Pineapple",
               ingredients: ["1 cup cottage cheese","½ cup pineapple chunks"],
               instructions: "Mix cottage cheese and pineapple.",
               calories: 220, protein: 20, carbs: 18, fat: 5),
        Recipe(name: "Chicken & Avocado Salad",
               ingredients: ["100g chicken","1 avocado","Mixed greens","Lime juice"],
               instructions: "Dice chicken + avocado; toss with greens and lime juice.",
               calories: 330, protein: 28, carbs: 8, fat: 18),
        Recipe(name: "Veggie Omelette",
               ingredients: ["2 eggs","1/4 cup bell peppers","1/4 cup onions","Spinach"],
               instructions: "Cook veggies; add beaten eggs; fold omelette when set.",
               calories: 250, protein: 18, carbs: 5, fat: 16),
        Recipe(name: "Peanut Butter Banana Sandwich",
               ingredients: ["2 slices bread","2 tbsp peanut butter","1 banana"],
               instructions: "Spread PB on bread; add banana slices; close sandwich.",
               calories: 350, protein: 12, carbs: 40, fat: 16),
        Recipe(name: "Shrimp & Zoodles",
               ingredients: ["150g shrimp","1 zucchini (spiralized)","1 tbsp olive oil","Garlic"],
               instructions: "Sauté garlic + shrimp; add zoodles; toss until tender.",
               calories: 300, protein: 25, carbs: 7, fat: 16),
        Recipe(name: "Pancakes with Berries",
               ingredients: ["1/2 cup pancake mix","1/2 cup milk","1/2 cup berries"],
               instructions: "Make pancakes per package; top with fresh berries.",
               calories: 320, protein: 8, carbs: 50, fat: 8),
        Recipe(name: "Chocolate Protein Pudding",
               ingredients: ["1 scoop chocolate protein","1/2 cup Greek yogurt","1 tbsp cocoa powder"],
               instructions: "Mix all ingredients until smooth.",
               calories: 200, protein: 22, carbs: 8, fat: 6),
        Recipe(name: "Apple & Almond Butter",
               ingredients: ["1 apple","2 tbsp almond butter"],
               instructions: "Slice apple; serve with almond butter.",
               calories: 210, protein: 5, carbs: 30, fat: 10),
        Recipe(name: "Turkey Meatballs & Marinara",
               ingredients: ["100g turkey meatballs","1/2 cup marinara sauce","1 serving pasta"],
               instructions: "Cook meatballs; serve with sauce and pasta.",
               calories: 400, protein: 28, carbs: 40, fat: 12)
    ]

    // MARK: – Adding new recipes (unchanged)
    func addManual(
        name: String,
        ingredients: [String],
        instructions: String,
        image: UIImage? = nil,
        completion: @escaping (Result<Recipe,Error>) -> Void
    ) { /*…*/ }
    func addFromText(
        _ text: String,
        completion: @escaping (Result<Recipe,Error>) -> Void
    ) { /*…*/ }
    func addFromImage(
        _ image: UIImage,
        description: String?,
        completion: @escaping (Result<Recipe,Error>) -> Void
    ) { /*…*/ }
}
